### PR TITLE
Wingtiptoys sample

### PR DESCRIPTION
**Pull request by birojnayak**
sample for Wingtiptoys

### CODE REVIEW

**Comment by twsouthwick** [comment]
Can you add just the framework at first? I'd like to try to have the samples only have a single directory and share source when enabling core (see the eshop sample)

**Comment by twsouthwick** [comment]
(you can add the core now if you want, just in the same folder)

**Comment by twsouthwick** [comment]
the core version can exclude what it needs to exclude initially if needed

**Comment by birojnayak** [comment]
@twsouthwick changed to the way you suggested. The core project is not fully compiling which I am going to work, but if you have some guidance around Owin, ping me over team.

**Review by twsouthwick — APPROVED** [review]
The folder "WingTipToys-Assets" and "WingTipToys-Src" seems weird - can it just be "assets" and "src"? Is that what it originally had?

Also, are you saying the framework code itself isn't working or the asp.net core version of it?

Other than that, LGTM

**Comment by twsouthwick** [comment]
> if you have some guidance around Owin, ping me over team.

I do - once you get this in, I'll pull the sample, take a look and let you know

**Pull request merged**
